In [4]:
import tensorflow as tf

# The file path to save the data
save_file = 'model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    sess.run(tf.initialize_all_variables())

    # Show the values of weights and bias
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    saver.save(sess, save_file)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
Weights:
[[-1.36403275  0.55637074  0.25009495]
 [ 1.03553987 -0.89692146 -1.22639406]]
Bias:
[ 0.91461217 -0.51340991  1.50004053]


ValueError: Parent directory of model.ckpt doesn't exist, can't save.